#pragma once
#define MAX_SERIAL_LEN 16
#define VENDOR_ID			0x28de
#define PRODUCT_ID			0x1205
#define ENDPOINT			3
#define CONTROLIDX			2
#define CHUNK_LENGTH		64
#define DISABLE_LIZARD_MODE_EVERY_X_INT 100
#define MAX_TRIGGER_VALUE 0x7FFF
#define MAX_STICK_AXIS_VALUE 0x7FFF

//#define DEBUG_BUTTON_PRESS
